# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chilly < Formula
  desc "Search chill.institute and send transfers from the terminal"
  homepage "https://chill.institute"
  version "2.4.7"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.4.7/chilly_2.4.7_darwin_amd64.tar.gz"
      sha256 "d381ee5b8f971ef39c14d4ec7fa6a0aef6dfe629c50a7acad9fcf9df770cc871"

      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.4.7/chilly_2.4.7_darwin_arm64.tar.gz"
      sha256 "b5d72c179f7cdcace6383039ef94d443ebdef55902d1465b7b286ab7587e9f88"

      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.4.7/chilly_2.4.7_linux_amd64.tar.gz"
      sha256 "08a8af805e8b80a4bbaeb153432359c9869161b582b4306f7bd243081c99c33f"
      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.4.7/chilly_2.4.7_linux_arm64.tar.gz"
      sha256 "46ac78212de5540392b4044f6b4983560f952437b8e9f155c035d3cd0b936fbd"
      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  test do
    system bin/"chilly", "version", "--output", "json"
  end
end
