# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chilly < Formula
  desc "Agent-first command line client for chill.institute"
  homepage "https://chill.institute"
  version "0.2.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chill-institute/chill-institute-cli/releases/download/v0.2.5/chilly_0.2.5_darwin_amd64.tar.gz"
      sha256 "a52a4c41259898ee9b70211238e5f14d16807d91ff613cf883602ae2040f2906"

      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chill-institute/chill-institute-cli/releases/download/v0.2.5/chilly_0.2.5_darwin_arm64.tar.gz"
      sha256 "d9afdcb56eff5d5f7ca7024ee287ebb4184b3c09e3663b2c6a444d90f8c3151b"

      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-institute-cli/releases/download/v0.2.5/chilly_0.2.5_linux_amd64.tar.gz"
      sha256 "e736769eae9042611e1acf88a40200ead7c5be6e10888c76ef600fb468e3cbaf"
      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-institute-cli/releases/download/v0.2.5/chilly_0.2.5_linux_arm64.tar.gz"
      sha256 "25333e7686c0e6835d9d9aeab2635696f07a7dcabbdf87a5035ddf89127decea"
      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  test do
    system "#{bin}/chilly", "version", "--output", "json"
  end
end
