# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chilly < Formula
  desc "Agent-first command-line client for chill.institute"
  homepage "https://chill.institute"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.1.1/chilly_2.1.1_darwin_amd64.tar.gz"
      sha256 "fb17883e20aab8176b84ba9fa508038a9c009796f519b7d24b46885e21c24313"

      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.1.1/chilly_2.1.1_darwin_arm64.tar.gz"
      sha256 "9a6ec4ae8b5a87812795c9b8c119a6dcf0d9b14fec00d2a71df5f3bbbbbb565c"

      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.1.1/chilly_2.1.1_linux_amd64.tar.gz"
      sha256 "a8af6507d1fb88e9f01c3b0256d92f09a6c1c137291ed138c360bb1aae3f53e9"
      define_method(:install) do
        bin.install "chilly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/chill-institute/chill-cli/releases/download/v2.1.1/chilly_2.1.1_linux_arm64.tar.gz"
      sha256 "c7809fd377d22a29d81338eb84afa995e1a01c87de3a6bef62157c9996444254"
      define_method(:install) do
        bin.install "chilly"
      end
    end
  end

  test do
    system bin/"chilly", "version", "--output", "json"
  end
end
